automation:
  enabled: true
  max_videos_per_day: 3
  schedule:
    - "09:00"  # 9:00 AM
    - "15:00"  # 3:00 PM  
    - "21:00"  # 9:00 PM

content:
  themes:
    - "motivacion"
    - "exito"
    - "emprendimiento"
    - "desarrollo_personal"
  
  video_specs:
    duration_seconds: 8
    resolution: "1080x1920"
    format: "mp4"
    fps: 30

tiktok:
  hashtags:
    - "#motivacion"
    - "#exito"
    - "#emprendimiento"
    - "#fyp"
    - "#viral"
  
  upload_settings:
    privacy: "public"
    allow_comments: true
    allow_duet: true
    allow_stitch: true

apis:
  gemini:
    model: "gemini-2.0-flash-preview-image-generation"
    temperature: 0.7
    max_tokens: 2048
  
  veo3:
    model: "models/veo-3.0-generate-preview"
    quality: "high"
    audio: true
